### ISSUE TITLE
划词翻译功能：建议改为可选项

### ISSUE THREAD

**Issue by cup113** [Kerinlin/translate-variable#1]
背景：有的时候复制代码需要`Ctrl+A`全选或者选中上千个字节，有时候会不小心把鼠标悬停在上面，它就会一下子翻译一堆东西，比如我昨天的记录：
![image](https://user-images.githubusercontent.com/87704389/178629533-ab497cee-11b7-4d4a-9fa7-3340aee42d6d.png)
（如图，我调用了16次，就使用了564个字符，正常使用翻译肯定不会这样的）
因此，我建议添加一个`AutoToCN`的选项，用户可以选择是否悬停即可。

**Comment by Kerinlin** [comment]
> 背景：有的时候复制代码需要`Ctrl+A`全选或者选中上千个字节，有时候会不小心把鼠标悬停在上面，它就会一下子翻译一堆东西，比如我昨天的记录： ![image](https://user-images.githubusercontent.com/87704389/178629533-ab497cee-11b7-4d4a-9fa7-3340aee42d6d.png) （如图，我调用了16次，就使用了564个字符，正常使用翻译肯定不会这样的） 因此，我建议添加一个`AutoToCN`的选项，用户可以选择是否悬停即可。

好建议，周末我抽空改一下

**Comment by Kerinlin** [comment]
@cup113 配置功能更新，但是我手欠删除了旧扩展，重新上传了新扩展，所以需要你删除旧扩展，然后安装新扩展，已配置的id，token这些不会重置

**Comment by cup113** [comment]
@Kerinlin OK，问题不大
