### ISSUE TITLE
命令：Translate to CN

### ISSUE THREAD

**Issue by cup113** [Kerinlin/translate-variable#4]
我从`VS Code`的“功能贡献”看到，激活事件中有`onCommand:translateVariable.toCN`，但是似乎`命令`中并没有：
![image](https://user-images.githubusercontent.com/87704389/178634405-5abe4089-dddb-4c2a-844a-4941b4b1cf74.png)
![image](https://user-images.githubusercontent.com/87704389/178634510-29d3a4f7-fee1-492c-a3d8-35bf9de75585.png)
不知道是不是漏加了？正好，我建议添加这个命令和[issue#1](https://github.com/Kerinlin/translate-variable/issues/1)结合一下，把是否默认划词翻译添加到设置里面，并把翻译其他语言到中文的行为改到命令里面，再弄一个快捷键。

**Comment by Kerinlin** [comment]
> 我从`VS Code`的“功能贡献”看到，激活事件中有`onCommand:translateVariable.toCN`，但是似乎`命令`中并没有： ![image](https://user-images.githubusercontent.com/87704389/178634405-5abe4089-dddb-4c2a-844a-4941b4b1cf74.png) ![image](https://user-images.githubusercontent.com/87704389/178634510-29d3a4f7-fee1-492c-a3d8-35bf9de75585.png) 不知道是不是漏加了？正好，我建议添加这个命令和[issue#1](https://github.com/Kerinlin/translate-variable/issues/1)结合一下，把是否默认划词翻译添加到设置里面，并把翻译其他语言到中文的行为改到命令里面，再弄一个快捷键。

感谢提建议，关于`onCommand:translateVariable.toCN`这个，之前是有考虑快捷键翻译成中文，但是后面因为换成了划词翻译，我认为功能重复了，所以其实代码中已经没有快捷键翻译成中文这个功能了，这个命令忘记删了，你能说一下你需要将其他语言翻译成中文的使用场景吗

**Comment by cup113** [comment]
这个场景倒是不需要，把#1解决一下就好了。主要是看到了这个命令，觉得有点奇怪
