### ISSUE TITLE
Cannot read properties of undefined (reading 'dst')

### ISSUE THREAD

**Issue by JohnsonSii** [Kerinlin/translate-variable#5]
Cannot read properties of undefined (reading 'dst')
How to resolve this warning

**Comment by cup113** [comment]
![image](https://user-images.githubusercontent.com/87704389/184138663-aee4d2dd-000b-4bc7-a30a-e74afcae2450.png)
Can you provide some logging from here, please?

**Comment by Kerinlin** [comment]
> Cannot read properties of undefined (reading 'dst') How to resolve this warning
![](https://camo.githubusercontent.com/38b6469f576830a3996964d4436f1b28946f8d32b0b56c658c06f469b77d35cf/68747470733a2f2f73322e6c6f6c692e6e65742f323032322f30312f30372f6e38656a44635a4962786d6b56454f2e706e67)
check if this is ok

**Comment by Kerinlin** [comment]
@JohnsonSii You can use lingva servic in the 0.2.0 version,it's free
